### PR TITLE
HLK-1

### PR DESCRIPTION
**Pull request by JasminFarhi**
Screen Shot 2022-11-01 at 10 21 21 am

### CODE REVIEW

**Review by OptimusOpus — APPROVED** [review]

**Comment by MikeyRobertson** [comment]
Can we please get a copy button next to the address (will add to ticket)

**Comment by bitcoinbrisbane** [comment]
This doesnt look good.  This is just a jpg.  Use a SVG package and create a pie chart

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
Dont just stick a png on please

**Review by xiangzhe0812 — APPROVED** [review]

**Comment by MikeyRobertson** [comment]
All good for now, we can change style/UI later

**Pull request merged**
